CREATE TABLE click_counter
(
    url_id          INTEGER                     NOT NULL,
    clicks          INTEGER                     NOT NULL,
    unique_clicks   INTEGER                     NOT NULL,
    last_clicked_at TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_click_counter PRIMARY KEY (url_id)
);

CREATE TABLE urls
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      INTEGER,
    short_url    VARCHAR(255)                             NOT NULL,
    original_url VARCHAR(255)                             NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   VARCHAR(255)                             NOT NULL,
    username  VARCHAR(255)                             NOT NULL,
    email     VARCHAR(255)                             NOT NULL,
    password  VARCHAR(255)                             NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    is_active BOOLEAN                                  NOT NULL,
    role      VARCHAR(255)                             NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD CONSTRAINT uc_urls_shorturl UNIQUE (short_url);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_userid UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_74165e195b2f7b25de690d14a ON users (email);

CREATE INDEX idx_77584fbe74cc86922be2a3560 ON users (username);

CREATE INDEX idx_d57b4f75072a4cbfbd54faa4d ON urls (short_url);

ALTER TABLE urls
    ADD CONSTRAINT fk_urls_user FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_93f7ffeb9f229a01aa86f23b6 ON urls (user_id);

ALTER TABLE click_counter
    ADD CONSTRAINT fk_click_counter_url FOREIGN KEY (url_id) REFERENCES urls (id);