CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   VARCHAR(255)                             NOT NULL,
    username  VARCHAR(255)                             NOT NULL,
    email     VARCHAR(255)                             NOT NULL,
    password  VARCHAR(255)                             NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    is_active BOOLEAN                                  NOT NULL,
    role      VARCHAR(255)                             NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_userid UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);